services:
  novai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novai-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend/server.js:/app/backend/server.js
      - ./frontend:/app/frontend
